test:integration:
  rules:
    - if: $RUN_TESTS_FULL_INTEGRATION == "true"
  services:
    - docker:${DOCKER_VERSION}-dind
  image: docker:${DOCKER_VERSION}-cli
  stage: test
  tags:
    - mender-qa-worker-integration-tests
  before_script:
    - |
      docker login registry.mender.io \
      --username $REGISTRY_MENDER_IO_USERNAME \
      --password $REGISTRY_MENDER_IO_PASSWORD
    - |
      docker login docker.io \
      --username $DOCKER_HUB_USERNAME \
      --password $DOCKER_HUB_PASSWORD
    - apk add $(cat ./tests/requirements-system/apk-requirements.txt)
    - apk add py3-virtualenv
    - python -m virtualenv /.venv
    - source /.venv/bin/activate
    - pip3 install -r ./tests/requirements-python/python-requirements.txt
  script:
    - cd tests
    - ./run.sh
