version: '2'
services:
    mender-backend-tests-runner:
        image: mender-backend-tests-runner
        networks:
            - mender
        volumes:
            - ${INTEGRATION_PATH}/backend-tests/tests:/tests
            - ${INTEGRATION_PATH}/testutils:/testutils
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - mender-api-gateway
        command: ${PYTEST_ARGS}
        environment:
            PYTHONPATH: "/testutils"
            PYTHONDONTWRITEBYTECODE: 1
